# Logging
CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=90000
CONFIG_USB_CDC_ACM=y
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_ZMK_BEHAVIOR_METADATA=y

# Debug section
#CONFIG_INPUT_LOG_LEVEL_DBG=y
#CONFIG_ZMK_LOG_LEVEL_DBG=y
#CONFIG_DEBUG=y
#CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=4000
